FROM python:3.7-slim

RUN mkdir app
WORKDIR /app

COPY requirements.txt /app
COPY model.joblib /app
COPY main.py /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--port=8000"]